#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker2221"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "10013afac1c7496cb6b70ae4935f7223" }
]

[assets]
directory = "./public"
